spring:
  application:
    name: UserService

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:microservices}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

jwt:
  secret: ${JWT_SECRET}
  service-token-expiration-ms: 300000